language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
env:
  - PACKAGE=confluent-oss
script:
  - brew audit $PACKAGE
  - brew install --verbose $PACKAGE
  - brew test $PACKAGE
